apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: harish1023/microservices-project-api-gateway:v3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: CONFIG_SERVER_URL
              value: "http://config-server:8888"
            - name: EUREKA_SERVER_URL
              value: "http://eureka-server:8761/eureka/"
            - name: ZIPKIN_ENDPOINT
              value: "http://zipkin:9411/api/v2/spans"