apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  mongo-uri: "mongodb+srv://JananiSivasankar:Janani2407@cluster0.rqcvycq.mongodb.net/ecommerceDB?retryWrites=true&w=majority&appName=Cluster0"
