apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: harish1023/microservices-project-order-service:v3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: CONFIG_SERVER_URL
              value: "http://config-server:8888"
            - name: EUREKA_SERVER_URL
              value: "http://eureka-server:8761/eureka/"
            - name: ZIPKIN_ENDPOINT
              value: "http://zipkin:9411/api/v2/spans"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/EcommerceDB"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root123"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-uri
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "guest"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "guest"